# Generated by Django 3.1.7 on 2021-12-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211201_2340'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'course_code')},
        ),
    ]
