# Generated by Django 3.1.7 on 2021-12-03 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211202_0203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('course_code', 'subject_name', 'credit', 'subtype')},
        ),
    ]
