# Generated by Django 3.1.7 on 2021-12-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211203_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.CharField(default='CSE', max_length=200),
            preserve_default=False,
        ),
    ]
