# Generated by Django 3.1.7 on 2021-11-29 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211130_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='email',
        ),
    ]
