# Generated by Django 3.1.7 on 2021-11-30 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211130_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='id',
        ),
        migrations.AddField(
            model_name='result',
            name='attendence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='course_code',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='marks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('credit', models.FloatField(null=True)),
                ('subtype', models.CharField(max_length=200, null=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.result')),
            ],
        ),
    ]
